### PR TITLE
docker-elk: add kibana 4 64bit

### PR DESCRIPTION
**Pull request by kotter**
This commit updates kibana 4.0.1 64 bit packages to the docker-elk
project.

updates elasticsearch repo to 1.4 as required for updating to
kibana 4.

### CODE REVIEW

**Comment by kotter** [comment]
@ChristianKniep taking a shot at the kibana 4 update.  I will test and show results shortly.  This project has been excellent for my work, so hoping to help you out a bit in return!

**Comment by ChristianKniep** [comment]
Cool, nicely done... I am currently extremly busy, but I will look into it and merge it. 
I heard good things about kibana 4 - it's time to check it out.

**Comment by ChristianKniep** [comment]
Hey @kotter, I had a first look. 
Do you mind creating a second PR to the branch kibana4 instead of master?
Furthermore, I would like to prevent binary blobs from lingering around in the repository.
I started it by puting rpms and tar.gzs all over the place, but you know - I was young and needed the space... 
If you just fetch kibana from the interweb using curl/wget.

I am going to check the new PR out at the weekend.

**Comment by kotter** [comment]
Ack-  I will update and resubmit.

**Comment by kotter** [comment]
> Do you mind creating a second PR to the branch kibana4 instead of master?

I'm not following here- can you clarify how you want me to submit my PR?  You want me to submit it as kibana4 branch instead of your master branch?  Sorry, I'm just a little confused.

**Pull request closed without merging**
