### PR TITLE
docker-elk: Update kibana to version 4

### PR DESCRIPTION
**Pull request by kotter**
This PR updates kibana to version 4.

Changes:

* pull the kibana tar image rather than storing them in the Docker
image
* remove kibana*.tar.gz files after unpackaging
* update elasticsearch repo to 1.4 as required for updating to
kibana 4

for more info, see:

http://www.elasticsearch.org/guide/en/kibana/current/setup.html

### CODE REVIEW

**Comment by kotter** [comment]
@ChristianKniep I think I got what you are looking for here.  Apologies if not.  if I get time today I will be testing this and let you know of the results.

**Comment by ChristianKniep** [comment]
Yeah, this is what I meant. :) 
Thx, I am going to have a look until Sunday, currently I have guests.

**Comment by ChristianKniep** [comment]
One remark; if you curl, unpack and remove the image in the same line the size of the intermediate images is going to be smaller. But that's just an optimization.

**Comment by kotter** [comment]
supersedes  https://github.com/ChristianKniep/docker-elk/pull/7

**Comment by kotter** [comment]
> One remark; if you curl, unpack and remove the image in the same line the size of the intermediate images is going to be smaller. But that's just an optimization.

I attempted this with my latest commit.

**Comment by ChristianKniep** [comment]
Hey @kotter,

alrighty then... There are some small pieces you have to adjust. As described in here:
https://github.com/ChristianKniep/docker-elk/compare/master...k4

- We can get rid of nginx now, since kibana4 is (yet another) jvm. :)
- you missed an ```&&``` in the downloading section. I also added ```-s``` which silences the download
- I added a kibana.ini to fire up kibana's jvm
- and the fig file was changed to spin it up

If you don't mind changing this in your PR, then I will merge it with my kibana4 branch and later 
it's going to be master.

Thx for pushing me to update. I guess I would have keept kibana3 for ages. :)

Cheers
Christian

**Comment by ChristianKniep** [comment]
I added a check_kibana.json to expose the kibana port via consul.

**Comment by kotter** [comment]
Ack- I'll try to get something in later today.  Thanks for the updates!

**Pull request closed without merging**
